#include "net_priv.h"

extern NetAPIDesc NET_PLAYER_NAME_API_DESC;
extern NetAPIDesc NET_REPLAY_DOWNLOAD_API_DESC;

NetAPIDesc NET_API_DESCS[] = {
    NET_PLAYER_NAME_API_DESC,
    NET_REPLAY_DOWNLOAD_API_DESC,
};

size_t NET_NUM_API_DESCS = ARRAYSIZE(NET_API_DESCS);
